<?php

namespace AppBundle\Repository;

/**
 * ObservationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationsRepository extends \Doctrine\ORM\EntityRepository {

    function getObservationsByBirdRace($race) {

        $qb = $this->createQueryBuilder('o')
            ->where('o.published = 1')
            ->andWhere('o.birdRace = :race')
            ->setParameter('race', $race)
            ->getQuery();

        $result = $qb->getResult();

        return $result;

    }

    function getAllObservations() {

        $qb = $this->createQueryBuilder('o')
            ->where('o.published = 1')
            ->getQuery();

        $result = $qb->getResult();

        return $result;

    }

}
