<?php

namespace AppBundle\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllByUsernameAsc() 
	{
		return $this
			->createQueryBuilder('u') // On construit la query qui recupère tous les users via le querybuilder
			->orderBy('u.username', 'ASC') // On les tri par username croissant
			->getQuery() // On crée la query
			->getResult(); // On retourne le résultat
	} // End findAllByUsername()


}
