<?php

namespace AppBundle\Repository;

/**
 * UsersPicturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersPicturesRepository extends \Doctrine\ORM\EntityRepository
{
}
