homepage:
    path: /
    defaults:
      _controller: "AppBundle:Default:index"

map:
    path: /map
    defaults:
      _controller: "AppBundle:Default:map"

add_observation:
    path: /add
    defaults:
      _controller: "AppBundle:Default:add"

dashboard:
    path: /dashboard
    defaults:
      _controller: "AppBundle:Default:dashboard"

user_list:
    path: /liste_utilisateur
    defaults:
      _controller: "AppBundle:Users:userList"

contact:
    path: /contact
    defaults:
      _controller: "AppBundle:Default:contact"

legal_notice:
    path: /legalNotice
    defaults:
      _controller: "AppBundle:Default:legalNotice"

tos:
    path: /termsOfService
    defaults:
      _controller: "AppBundle:Default:tos"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profil

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /inscription

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /motdepasseperdu

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profil

app:
    resource: '@AppBundle/Controller/'
    type: annotation

promote_user:
    path: "/naturaliser_utilisateur/{id}"
    defaults:
      _controller: "AppBundle:Users:promoteUser"

demote_user:
    path: "/retrograder_utilisateur/{id}"
    defaults:
      _controller: "AppBundle:Users:demoteUser"

remove_user:
    path: "/supprimer_utilisateur/{id}"
    defaults:
      _controller: "AppBundle:Users:removeUser"




