<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2xukfrt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2xukfrt/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2xukfrt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2xukfrt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2xukfrt\appProdProjectContainer(array(
    'container.build_hash' => '2xukfrt',
    'container.build_id' => 'db26a3a8',
    'container.build_time' => 1515983015,
));
