<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCxftdwe\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCxftdwe/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCxftdwe.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCxftdwe\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCxftdwe\appProdProjectContainer();
