<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNefmvnk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNefmvnk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNefmvnk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNefmvnk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNefmvnk\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Nefmvnk',
    'container.build_id' => 'ae425440',
    'container.build_time' => 1516867351,
));
