<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1vkis1g\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1vkis1g/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1vkis1g.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1vkis1g\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container1vkis1g\appDevDebugProjectContainer(array(
    'container.build_hash' => '1vkis1g',
    'container.build_id' => '1fa1fb50',
    'container.build_time' => 1516010679,
));
