<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYp3icd6\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYp3icd6/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYp3icd6.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYp3icd6\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYp3icd6\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Yp3icd6',
    'container.build_id' => 'cad5bfeb',
    'container.build_time' => 1516873880,
));
